name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test


name: Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Sum Test
        run: npm test ./__tests__/sum.test.js
      - name: Unit Tests
        run: npm test ./__tests__/unit.test.js